### ISSUE TITLE
Unknown ssh-ed25519 host key

### ISSUE THREAD

**Issue by glesage** [chaplyk/docker-compose-remote-action#5]
Hi peeps, thank you very much for this GH action!

I'm having an issue running this against a Fresh Ubuntu 22.04 instance on Digital Ocean, everything seems to run smoothly on the machine, SSH is setup with rsa key and all looks good.

but I get this error `Unknown ssh-ed25519 host key`

Here is a screenshot of the step:
<img width="1069" alt="Screenshot 2023-07-08 at 10 39 08 PM" src="https://github.com/chaplyk/docker-compose-remote-action/assets/711580/30fc4696-25a2-4b0e-aad0-527659de6f2c">

The full error is:
```
[26] Failed to execute script docker-compose
/tmp/_MEIaEbEnI/paramiko/client.py:837: UserWarning: Unknown ssh-ed25519 host key for 170.64.163.217: b'a6293bdc2e5419624972ece8143ac300'
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 125, in perform_command
  File "compose/cli/command.py", line 76, in project_from_options
  File "compose/cli/command.py", line 142, in get_project
  File "compose/cli/docker_client.py", line 47, in get_client
  File "compose/cli/docker_client.py", line 174, in docker_client
  File "site-packages/docker/api/client.py", line 166, in __init__
  File "site-packages/docker/transport/sshconn.py", line 111, in __init__
  File "site-packages/docker/transport/sshconn.py", line 119, in _connect
  File "site-packages/paramiko/client.py", line [44](https://github.com/glesage/frodo/actions/runs/5494427672/jobs/10013213891#step:7:45)6, in connect
  File "site-packages/paramiko/client.py", line 764, in _auth
  File "site-packages/paramiko/client.py", line 700, in _auth
  File "site-packages/paramiko/transport.py", line 1580, in auth_publickey
  File "site-packages/paramiko/auth_handler.py", line 2[50](https://github.com/glesage/frodo/actions/runs/5494427672/jobs/10013213891#step:7:51), in wait_for_response
```

I can't seem to figure out why that is, I tried:
1. generating an `ed25519` ssh key
2. Deleting `known_hosts`
3. Removing the global `/etc/ssh/ssh_host_ed25519_key`
4. Doing exactly the commands in [/entrypoint.sh](/entrypoint.sh) locally and they work correctly --> I'm able to run the deployment from my local machine just like this GH Action should

Still no luck. Let me know if you have any thoughts

**Comment by glesage** [comment]
Figured it out... it's just a warning but it was due to host key not being verified indeed https://github.com/chaplyk/docker-compose-remote-action/pull/6
